apiVersion: apps/v1
kind: Deployment
metadata:
  name: trand-alpine
  labels:
    app: alpine
spec:
  replicas: 5
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      name: alpine-pod
      labels:
        app: alpine
    spec:
      containers:
      - name: my-alpine
        image: myalpine:3.15
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "watch -n 2 date"]
 
